#!/bin/sh

$HOME/linuxc/startup.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4

bspc config border_width 2
bspc config window_gap 30

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config top_padding 70
bspc config bottom_padding 0

#bspc config normal_border_color
#bspc config focused_border_color

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config split_ratio 0.5
