#!/bin/sh
xrandr --dpi 150

$HOME/linuxc/startup.sh &

pkill sxhkd  

sxhkd &

$HOME/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 30

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config top_padding 50
bspc config bottom_padding 0

bspc config normal_border_color \#e0e0e0
bspc config focused_border_color \#e0e0e0

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config split_ratio 0.5

bspc rule -a Xfce4-appfinder state=floating center=true
