#!/bin/sh

$HOME/linuxc/startup.sh &

pkill sxhkd

sxhkd &

$HOME/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 4
bspc config window_gap 40

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config top_padding 60
bspc config bottom_padding 10
bspc config left_padding 10
bspc config right_padding 10

bspc config normal_border_color \#e0e0e0
bspc config focused_border_color \#d70a53

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config split_ratio 0.5

bspc rule -a Xfce4-appfinder state=floating center=true

# bspc rule -a * floating=on
